spring:
  activemq:
    broker-url: ${ACTIVEMQ_BROKER_URL}
    user: ${ACTIVEMQ_USER}
    password: ${ACTIVEMQ_PASSWORD}

logging:
  level:
    root: WARN
    org.springframework: WARN
    com.gym.crm: INFO