spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: gymuser
    password: gympass
  data:
    mongodb:
      uri: mongodb://localhost:27017/workload_db

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.gym.crm: DEBUG