spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: gym-core-service
          uri: lb://gym-core-service
          predicates:
            - Path=/gym-crm/core/**
          filters:
            - name: CircuitBreaker
              args:
                name: gymCoreCircuitBreaker
                fallbackUri: forward:/fallback/core
        - id: workload-service
          uri: lb://workload-service
          predicates:
            - Path=/gym-crm/workload/**
          filters:
            - name: CircuitBreaker
              args:
                name: workloadCircuitBreaker
                fallbackUri: forward:/fallback/workload

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL}

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}

resilience4j:
  circuitbreaker:
    instances:
      gymCoreCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
      workloadCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s