spring:
  application:
    name: discovery-service

server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "health"
  endpoint:
    health:
      show-details: always