spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: false
  activemq:
    broker-url: ${ACTIVEMQ_BROKER_URL}
    user: ${ACTIVEMQ_USER}
    password: ${ACTIVEMQ_PASSWORD}

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.gym.crm: INFO

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL}
  instance:
    prefer-ip-address: true

app:
  services:
    workload:
      url: ${WORKLOAD_SERVICE_URL}